#cloud-config

hostname: node2
locale: "en_US.UTF-8"
timezone: "Europe/Berlin"

users:
  - name: racoon
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }