#cloud-config

hostname: node1
manage_etc_hosts: true
locale: "en_US.UTF-8"

users:
  - name: pirate
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video,input
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxWCf7JEybhoFH4UpB6rT48SQtBPHXXZojUH/JupYrPX79oLRxX/QNLFuWYRR9n0as9b/n4bxsNmxZio/lqSnnS12ct2thpL4sEEa180D6VIpZ5U0YIqgz1SrzOqO5V+zB4w52i2qjajzThRDbf05c4vIQ4dJqRcK4DNgBe0AuUiSuHiThO9c5kyGFo+dm+iHbT81t2M+svFt/PDWjh2L0j1PQR6ADMIdPM/k601fWgJkZZGtFGd4v+DS1iOuQSRW3LG8PbbvQpZyfgI3MX/HvJ3BHZ5h2XnbKySOXOuhAqdceKH4GbE9J/C5HgFSAnxvrBBM+jA0GRvfMiYXV2mgWDnUL5QMZKn99ASYNn8Q4mQNbXGS9rVjlOuml62z5Kx2+qGxNYML2bwEny0tek34zuzUWARoF/enqccPjT4O5ZUUS5+WMn3fCmyx7xE3/QDB2V/YeqvnP5KRS2jtUqwKb455QAUKlrYBcnxcKyHlBT99ScF+1IyxOZO1bycV9xaSK88ikH0R2FTI5tyt3zfS+ql+sQuEYFAcYkZafIhJawoCDA28Oc6hDyH3bQ5I12oLsGvzvBRiQm7OvHy2mGmvRyJkL1m7fyDW0l7fljO1lybL+ARkKOm51PRDuCKUqq8y892MBQrApZbSjQC83HsN/5Y8EkU2vFlKqYK6ubnvGGw== p.lubach@C02XRL33JG5J.fritz.box
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ2FXCCyB3n1D1CsBPx/2aF6VczxMhbu5yIW3Cd/+MNW p.lubach@reply.de
  - name: racoon
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker
    plain_text_passwd: hypriot
    lock_passwd: true
    ssh_pwauth: true
    chpasswd: { expire: false }
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxWCf7JEybhoFH4UpB6rT48SQtBPHXXZojUH/JupYrPX79oLRxX/QNLFuWYRR9n0as9b/n4bxsNmxZio/lqSnnS12ct2thpL4sEEa180D6VIpZ5U0YIqgz1SrzOqO5V+zB4w52i2qjajzThRDbf05c4vIQ4dJqRcK4DNgBe0AuUiSuHiThO9c5kyGFo+dm+iHbT81t2M+svFt/PDWjh2L0j1PQR6ADMIdPM/k601fWgJkZZGtFGd4v+DS1iOuQSRW3LG8PbbvQpZyfgI3MX/HvJ3BHZ5h2XnbKySOXOuhAqdceKH4GbE9J/C5HgFSAnxvrBBM+jA0GRvfMiYXV2mgWDnUL5QMZKn99ASYNn8Q4mQNbXGS9rVjlOuml62z5Kx2+qGxNYML2bwEny0tek34zuzUWARoF/enqccPjT4O5ZUUS5+WMn3fCmyx7xE3/QDB2V/YeqvnP5KRS2jtUqwKb455QAUKlrYBcnxcKyHlBT99ScF+1IyxOZO1bycV9xaSK88ikH0R2FTI5tyt3zfS+ql+sQuEYFAcYkZafIhJawoCDA28Oc6hDyH3bQ5I12oLsGvzvBRiQm7OvHy2mGmvRyJkL1m7fyDW0l7fljO1lybL+ARkKOm51PRDuCKUqq8y892MBQrApZbSjQC83HsN/5Y8EkU2vFlKqYK6ubnvGGw== p.lubach@C02XRL33JG5J.fritz.box
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ2FXCCyB3n1D1CsBPx/2aF6VczxMhbu5yIW3Cd/+MNW p.lubach@reply.de

# # Set the timezone
# # Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: "Europe/Berlin"

# # Update apt packages on first boot
# package_update: true
# package_upgrade: true
# package_reboot_if_required: true
package_upgrade: false

packages:
  - git
  - vim

# static IP address configuration
write_files:
  - content: |
      persistent
      # Generate Stable Private IPv6 Addresses instead of hardware based ones
      slaac private
      # static IP configuration:
      interface eth0
      static ip_address=192.168.178.100/24
      # static ip6_address=fd51:42f8:caae:d92e::ff/64
      static routers=192.168.178.1
      static domain_name_servers=192.168.178.1 1.1.1.1 1.0.0.1
    path: /etc/dhcpcd.conf

runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'